default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kvatnik
  password: 5544
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_sun_tutorial_development

test:
  <<: *default
  database: rails_sun_tutorial_test
